<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getWeeklyStats } from '@/api/stats'
import { capabilityForPath } from '@/config/capabilities'
import type { AppRequestError } from '@/lib/errors'
import { formatMastery, weeklyLearningLabel } from '@/lib/report'
import type { WeeklyStatsDto } from '@/types/api'
const stats=ref<WeeklyStatsDto|null>(null);const error=ref('');const loading=ref(false);const capability=capabilityForPath('/api/v1/users/me/stats/weekly');const accuracy=computed(()=>stats.value&&stats.value.answeredQuestions>0?Math.round(stats.value.correctQuestions/stats.value.answeredQuestions*100):null)
async function load(){error.value='';if(!capability.availableInCurrentServer){error.value='周报聚合接口尚未在当前分支后端实现；这里不会用本地估算冒充正式学习统计。';return}loading.value=true;try{stats.value=await getWeeklyStats()}catch(e){error.value=(e as AppRequestError).message||'周报加载失败'}finally{loading.value=false}}onShow(load)
</script>
<template><view class="ruankao-page"><text class="eyebrow">WEEKLY</text><text class="title">这一周，学到了哪里</text><view v-if="stats"><text class="period">{{stats.weekStart}} — {{stats.weekEnd}}</text><view class="hero ruankao-card"><text class="big">{{weeklyLearningLabel(stats.studyMinutes)}}</text><view class="metrics"><view><text class="n">{{stats.completedTasks}}</text><text>完成任务</text></view><view><text class="n">{{stats.answeredQuestions}}</text><text>答题</text></view><view><text class="n">{{accuracy==null?'—':accuracy+'%'}}</text><text>正确率</text></view></view></view><view class="weak"><text class="section">需要多看一眼</text><view v-for="k in stats.weakKnowledge" :key="k.knowledgeId" class="ruankao-card item" @tap="uni.navigateTo({url:`/pages/knowledge/detail?id=${k.knowledgeId}`})"><text>{{k.name}}</text><text class="mastery">{{formatMastery(k.masteryScore,k.evidenceCount)}}</text></view></view></view><text v-if="loading" class="muted">生成周报…</text><view v-if="error" class="notice">{{error}}</view></view></template>
<style scoped>.eyebrow{color:#3658d4;font-size:22rpx;font-weight:800;letter-spacing:4rpx}.title{display:block;margin-top:12rpx;font-size:42rpx;font-weight:850}.period{display:block;margin-top:12rpx;color:#98a2b3;font-size:22rpx}.hero{margin-top:30rpx;padding:30rpx}.big{font-size:31rpx;font-weight:850}.metrics{display:grid;grid-template-columns:repeat(3,1fr);margin-top:30rpx}.metrics view{display:flex;flex-direction:column;gap:7rpx;color:#7b8498;font-size:21rpx}.n{color:#172033;font-size:35rpx;font-weight:900}.weak{margin-top:36rpx}.section{font-size:29rpx;font-weight:800}.item{display:flex;justify-content:space-between;margin-top:14rpx;padding:24rpx;font-size:25rpx}.mastery{color:#3658d4;font-weight:800}.notice{margin-top:28rpx;padding:24rpx;border-radius:20rpx;background:#fff6e5;color:#8a5a00;font-size:24rpx;line-height:1.65}.muted{display:block;margin-top:24rpx;color:#7b8498}</style>
