<script setup lang="ts">
import { ref } from 'vue'
import { askAi } from '@/api/ai'
import { capabilityForPath } from '@/config/capabilities'
import type { AppRequestError } from '@/lib/errors'
const capability=capabilityForPath('/api/v1/ai/chat');const input=ref('');const answer=ref('');const error=ref('');const loading=ref(false)
async function send(){const message=input.value.trim();if(!message)return;error.value='';answer.value='';if(!capability.availableInCurrentServer){error.value='AI Layer 尚未在当前分支后端实现。学习、视频和做题不会依赖 AI，后端接入 Provider 后这里会直接启用。';return}loading.value=true;try{answer.value=(await askAi(message)).content}catch(e){error.value=(e as AppRequestError).message||'AI 暂时不可用，你仍可继续正常学习'}finally{loading.value=false}}
</script>
<template><view class="ruankao-page"><text class="eyebrow">AI TUTOR</text><text class="title">不会的地方，换一种讲法</text><text class="desc">AI 用于解释、举例和学习建议，不计算掌握度，也不会改标准答案。</text><view v-if="!capability.availableInCurrentServer" class="notice">当前后端 Phase 5 AI Layer 尚未完成，因此不会返回伪造的 AI 回复。</view><textarea v-model="input" class="input ruankao-card" placeholder="输入你想理解的问题…" maxlength="1000"/><button class="primary" :loading="loading" @tap="send">问 AI</button><view v-if="answer" class="answer ruankao-card">{{answer}}</view><view v-if="error" class="error">{{error}}</view></view></template>
<style scoped>.eyebrow{color:#7a42d8;font-size:22rpx;font-weight:800;letter-spacing:4rpx}.title{display:block;margin-top:12rpx;font-size:42rpx;line-height:1.4;font-weight:850}.desc{display:block;margin-top:18rpx;color:#667085;font-size:25rpx;line-height:1.7}.notice{margin-top:28rpx;padding:24rpx;border-radius:20rpx;background:#f5efff;color:#6934bd;font-size:24rpx;line-height:1.65}.input{width:100%;box-sizing:border-box;min-height:240rpx;margin-top:28rpx;padding:28rpx;font-size:27rpx}.primary{margin-top:20rpx;border-radius:22rpx;background:#172033;color:#fff;font-weight:700}.answer{margin-top:28rpx;padding:30rpx;color:#344054;font-size:26rpx;line-height:1.75;white-space:pre-wrap}.error{margin-top:24rpx;color:#9b5c00;font-size:24rpx;line-height:1.6}</style>
