<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { startQuestionSession } from '@/api/practice'
import { capabilityForPath } from '@/config/capabilities'
import type { AppRequestError } from '@/lib/errors'
import type { PracticeSource } from '@/types/api'
const error=ref(''); const loading=ref(false); const initialSource=ref<PracticeSource>('REAL_EXAM'); const capability=capabilityForPath('/api/v1/question-sessions')
onLoad(q=>{const s=String(q?.source||'REAL_EXAM') as PracticeSource;if(['CHAPTER','REAL_EXAM','WRONG_REVIEW','AI_QUIZ'].includes(s))initialSource.value=s})
async function start(source:PracticeSource){error.value='';if(!capability.availableInCurrentServer){error.value='当前分支后端尚未开放通用题目会话 REST 接口；题库交互已就绪，接口上线后即可开始真实练习。';return}loading.value=true;try{const r=await startQuestionSession({source});uni.navigateTo({url:`/pages/practice/session?sessionId=${r.sessionId}&source=${source}`})}catch(e){error.value=(e as AppRequestError).message||'练习暂时无法开始'}finally{loading.value=false}}
</script>
<template><view class="ruankao-page"><text class="eyebrow">PRACTICE</text><text class="title">每道题，都变成下一次会的证据</text><view class="grid"><view class="entry primary" @tap="start(initialSource)"><text class="num">01</text><text>开始练习</text><text class="sub">按当前学习任务进入</text></view><view class="entry" @tap="start('REAL_EXAM')"><text class="num">02</text><text>历年真题</text><text class="sub">只展示标记为 REAL_EXAM 的题</text></view><view class="entry" @tap="start('CHAPTER')"><text class="num">03</text><text>章节练习</text><text class="sub">跟着知识体系练</text></view><view class="entry" @tap="uni.navigateTo({url:'/pages/practice/wrong'})"><text class="num">04</text><text>错题本</text><text class="sub">回看 ACTIVE / MASTERED 历史</text></view><view class="entry" @tap="uni.navigateTo({url:'/pages/practice/favorites'})"><text class="num">05</text><text>我的收藏</text><text class="sub">当前为本机收藏</text></view></view><text v-if="loading" class="muted">正在创建练习…</text><view v-if="error" class="notice">{{error}}</view></view></template>
<style scoped>.eyebrow{color:#3658d4;font-size:22rpx;font-weight:800;letter-spacing:4rpx}.title{display:block;margin:12rpx 0 34rpx;font-size:40rpx;line-height:1.4;font-weight:850}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18rpx}.entry{min-height:190rpx;padding:28rpx;border-radius:26rpx;background:#fff;display:flex;flex-direction:column;font-size:28rpx;font-weight:800}.entry.primary{grid-column:1/3;background:#172033;color:#fff}.num{color:#3658d4;font-size:22rpx;margin-bottom:auto}.primary .num{color:#90a5ff}.sub{margin-top:12rpx;color:#98a2b3;font-size:21rpx;font-weight:500;line-height:1.5}.muted{display:block;margin-top:24rpx;color:#7b8498}.notice{margin-top:26rpx;padding:24rpx;border-radius:20rpx;background:#fff6e5;color:#8a5a00;font-size:24rpx;line-height:1.6}</style>
