<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { listSessionQuestions, submitQuestionAnswer } from '@/api/practice'
import { buildAnswerValue, toggleChoice } from '@/lib/practice'
import type { AppRequestError } from '@/lib/errors'
import { useFavoritesStore } from '@/stores/favorites'
import type { AnswerConfidence, PracticeQuestionDto, PracticeSource, QuestionAnswerFeedbackDto } from '@/types/api'
const sessionId=ref('');const source=ref<PracticeSource>('CHAPTER');const questions=ref<PracticeQuestionDto[]>([]);const index=ref(0);const selected=ref<string[]>([]);const textAnswer=ref('');const confidence=ref<AnswerConfidence>('UNCERTAIN');const feedback=ref<QuestionAnswerFeedbackDto|null>(null);const error=ref('');const loading=ref(false);const startedAt=ref(Date.now());const favorites=useFavoritesStore();const current=computed(()=>questions.value[index.value]);const answer=computed(()=>current.value&&['SINGLE_CHOICE','MULTIPLE_CHOICE'].includes(current.value.type)?buildAnswerValue(selected.value,current.value.type):textAnswer.value.trim())
onLoad(async q=>{sessionId.value=String(q?.sessionId||'');source.value=String(q?.source||'CHAPTER') as PracticeSource;favorites.restore();try{questions.value=await listSessionQuestions(sessionId.value)}catch(e){error.value=(e as AppRequestError).message||'题目加载失败'}})
function choose(key:string){if(!current.value)return;selected.value=toggleChoice(selected.value,key,current.value.type)}
async function submit(){if(!current.value||!answer.value){error.value='请先作答';return}loading.value=true;error.value='';try{feedback.value=await submitQuestionAnswer(sessionId.value,{questionId:current.value.id,answer:answer.value,durationSeconds:Math.round((Date.now()-startedAt.value)/1000),confidence:confidence.value,source:source.value})}catch(e){error.value=(e as AppRequestError).message||'提交失败'}finally{loading.value=false}}
function next(){if(index.value>=questions.value.length-1){uni.navigateBack();return}index.value++;selected.value=[];textAnswer.value='';feedback.value=null;confidence.value='UNCERTAIN';startedAt.value=Date.now()}
</script>
<template><view class="ruankao-page"><view v-if="current"><view class="head"><text>{{index+1}} / {{questions.length}}</text><button class="fav" @tap="favorites.toggle(current)">{{favorites.has(current.id)?'★ 已收藏':'☆ 收藏'}}</button></view><view class="question ruankao-card"><text class="meta">{{current.type}} · {{current.difficulty}}</text><text class="content">{{current.content}}</text><view v-if="current.options?.length" class="options"><button v-for="o in current.options" :key="o.key" class="option" :class="{active:selected.includes(o.key)}" @tap="choose(o.key)">{{o.key}}. {{o.text}}</button></view><textarea v-else v-model="textAnswer" class="textarea" placeholder="请输入答案"/><view class="confidence"><button v-for="x in [{v:'GUESS',t:'蒙的'},{v:'UNCERTAIN',t:'不确定'},{v:'CONFIDENT',t:'确定'}]" :key="x.v" class="chip" :class="{active:confidence===x.v}" @tap="confidence=x.v as AnswerConfidence">{{x.t}}</button></view></view><view v-if="feedback" class="feedback ruankao-card"><text class="result" :class="{ok:feedback.correct}">{{feedback.correct?'回答正确':'回答错误'}}</text><text v-if="feedback.standardAnswer" class="line">标准答案：{{feedback.standardAnswer}}</text><text v-if="feedback.explanation" class="explain">{{feedback.explanation}}</text><button class="primary" @tap="next">{{index===questions.length-1?'完成练习':'下一题'}}</button></view><button v-else class="primary" :loading="loading" @tap="submit">提交答案</button></view><text v-else-if="!error" class="empty">暂无题目</text><text v-if="error" class="error">{{error}}</text></view></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:center;color:#667085;font-size:23rpx}.fav{margin:0;background:transparent;color:#3658d4;font-size:23rpx}.question,.feedback{margin-top:20rpx;padding:30rpx}.meta{color:#667085;font-size:22rpx}.content{display:block;margin-top:18rpx;font-size:31rpx;line-height:1.7;font-weight:700}.options{display:flex;flex-direction:column;gap:15rpx;margin-top:26rpx}.option{margin:0;text-align:left;border-radius:20rpx;background:#f7f8fc;color:#344054;font-size:25rpx}.option.active{background:#e8edff;color:#2946b8}.textarea{width:100%;box-sizing:border-box;min-height:180rpx;margin-top:24rpx;padding:20rpx;border-radius:18rpx;background:#f7f8fc}.confidence{display:flex;gap:12rpx;margin-top:28rpx}.chip{flex:1;margin:0;border-radius:999rpx;background:#f2f4f7;color:#667085;font-size:22rpx}.chip.active{background:#e8edff;color:#3658d4}.primary{margin-top:26rpx;border-radius:22rpx;background:#3658d4;color:#fff;font-weight:700}.result{display:block;color:#c43d3d;font-size:30rpx;font-weight:850}.result.ok{color:#16a36a}.line,.explain{display:block;margin-top:16rpx;color:#475467;font-size:25rpx;line-height:1.7}.error,.empty{display:block;margin-top:30rpx;color:#c43d3d}.empty{color:#98a2b3}</style>
